"""empty message

Revision ID: 9e446fc03ba5
Revises: a0841e732229
Create Date: 2024-07-23 15:56:29.437787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e446fc03ba5'
down_revision = 'a0841e732229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=120), nullable=True))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homework_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('homework_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homework_num', sa.INTEGER(), nullable=True))
        batch_op.drop_column('homework_name')

    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
